### ISSUE TITLE
Customer card

### ISSUE THREAD

**Issue by Avi888** [yayasoft/ytour#231] opened 2015-01-04 12:10 UTC
![customer-card](https://cloud.githubusercontent.com/assets/8790191/5605849/7d0f2dd8-941b-11e4-8554-a455cdbf8130.png)

**Comment by feigale** [comment] 2015-01-05 09:09
![231](https://cloud.githubusercontent.com/assets/8790628/5611152/c5a06b3a-94ec-11e4-9313-6977e92ad9b6.png)

**Comment by suhrab** [comment] 2015-01-05 10:19
Somebody give priority to this issue

**Comment by suhrab** [comment] 2015-01-06 12:27
https://github.com/polymer/observe-js
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/observe

**Comment by novice3030** [comment] 2015-01-06 13:27
This is not a bug!
When entity state is Added manager.hasChanges will return true. 
this is the normal behavior and should not be changed.
Adding a new entity to the manager is also a change and you should ask the user if you wants to save changes when closing the dialog

**Closed as completed** 2015-01-27 12:07 UTC
Labels: not a bug
